import { auth, db } from './firebase-config.js';
import { getCurrentProfile } from './security.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js';
import { collection, getDocs, onSnapshot, query, where, limit, doc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const initials=name=>String(name||'U').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const formatDate=value=>value?.toDate?value.toDate().toLocaleDateString('es-MX',{day:'2-digit',month:'2-digit'}):'';

onAuthStateChanged(auth,async user=>{
  if(!user)return;
  const profile=await getCurrentProfile(user);if(!profile)return;
  const role=profile.rol,assignedGroups=new Set();let messages=[],contacts=[],view='messages',firstSnapshot=true;
  const style=document.createElement('link');style.rel='stylesheet';style.href='css/message-widget.css';document.head.appendChild(style);
  const root=document.createElement('div');root.className='message-widget';root.innerHTML=`<button class="mw-launcher" aria-label="Abrir mensajes"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 5h16v12H7l-3 3z"/><path d="M8 9h8M8 13h5"/></svg><span class="mw-count"></span></button><aside class="mw-drawer"><header class="mw-head"><span class="mw-avatar">${initials(profile.nombre)}</span><div><strong>${escapeHtml(profile.nombre||user.email)}</strong><span>Mensajería escolar · ${escapeHtml(role)}</span></div><button class="mw-close">×</button></header><div class="mw-toolbar"><input class="mw-search" placeholder="Buscar mensajes o contactos"><div class="mw-tabs"><button class="active" data-mw-view="messages">Mensajes</button><button data-mw-view="contacts">Contactos</button></div></div><div class="mw-list"></div><footer class="mw-footer"><a href="centro-mensajes.html">Abrir centro de comunicaciones</a></footer></aside>`;document.body.appendChild(root);
  const drawer=root.querySelector('.mw-drawer'),list=root.querySelector('.mw-list'),badge=root.querySelector('.mw-count'),search=root.querySelector('.mw-search');
  const[usersSnap,subjectsSnap]=await Promise.all([getDocs(collection(db,'usuarios')),getDocs(collection(db,'materias'))]);
  contacts=usersSnap.docs.map(item=>({id:item.id,...item.data()})).filter(item=>item.uid&&item.activo!==false&&item.id!==user.uid);
  if(role==='maestro')subjectsSnap.docs.map(item=>item.data()).filter(item=>String(item.maestro_email||'').toLowerCase()===String(user.email).toLowerCase()).forEach(item=>{if(item.grupo)assignedGroups.add(String(item.grupo));});
  function receives(data){if(data.creadoPorUid===user.uid)return false;if(['superadmin','directora'].includes(role))return true;if(role==='recepcion')return data.destinatarioTipo==='colegio'||(data.destinatarioTipo==='usuario'&&[user.uid,user.email].includes(data.destinatarioId));if(data.destinatarioTipo==='colegio'||data.destinatarioTipo==='docentes')return true;if(data.destinatarioTipo==='usuario')return[user.uid,user.email,profile.usuario,profile.usuario_original].filter(Boolean).includes(data.destinatarioId);if(data.destinatarioTipo==='grupo')return assignedGroups.has(String(data.destinatarioId));if(data.destinatarioTipo==='nivel')return[...assignedGroups].some(group=>group.toLowerCase().includes(String(data.destinatarioId).toLowerCase()));return false;}
  const unread=()=>messages.filter(item=>receives(item.data)&&!localStorage.getItem(`msg-read-${item.id}`));
  function render(){const term=search.value.toLowerCase().trim();root.querySelectorAll('[data-mw-view]').forEach(x=>x.classList.toggle('active',x.dataset.mwView===view));if(view==='contacts'){const items=contacts.filter(x=>`${x.nombre} ${x.usuario} ${x.email} ${x.rol}`.toLowerCase().includes(term));list.innerHTML=items.length?items.map(x=>`<a class="mw-contact" href="centro-mensajes.html?to=${encodeURIComponent(x.id)}"><span class="mw-contact-avatar">${initials(x.nombre)}</span><div><strong>${escapeHtml(x.nombre||x.usuario||x.email)}</strong><span>${escapeHtml(x.rol)} · ${escapeHtml(x.usuario_original||x.email)}</span></div></a>`).join(''):'<div class="mw-empty">No se encontraron contactos.</div>';return;}const items=messages.filter(item=>receives(item.data)&&`${item.data.titulo} ${item.data.mensaje} ${item.data.creadoPorNombre}`.toLowerCase().includes(term));list.innerHTML=items.length?items.map(({id,data})=>`<button class="mw-item ${localStorage.getItem(`msg-read-${id}`)?'':'unread'}" data-mw-message="${id}"><span class="mw-item-top"><strong>${escapeHtml(data.creadoPorNombre||'Personal escolar')}</strong><time>${formatDate(data.creadoEn)}</time></span><p>${escapeHtml(data.titulo)} · ${escapeHtml(data.mensaje)}</p></button>`).join(''):'<div class="mw-empty">No tienes mensajes en esta vista.</div>';list.querySelectorAll('[data-mw-message]').forEach(button=>button.addEventListener('click',async()=>{localStorage.setItem(`msg-read-${button.dataset.mwMessage}`,'1');await setDoc(doc(db,'avisos',button.dataset.mwMessage,'lecturas',user.uid),{uid:user.uid,nombre:profile.nombre||user.email,leidoEn:serverTimestamp()},{merge:true}).catch(()=>{});window.location.href=`centro-mensajes.html#${button.dataset.mwMessage}`;}));const count=unread().length;badge.textContent=count>99?'99+':count;badge.classList.toggle('visible',count>0);}
  function toast(data){root.querySelector('.mw-toast')?.remove();const toast=document.createElement('div');toast.className='mw-toast';toast.innerHTML=`<strong>Nuevo mensaje de ${escapeHtml(data.creadoPorNombre||'personal escolar')}</strong><span>${escapeHtml(data.titulo)}</span>`;root.appendChild(toast);setTimeout(()=>toast.remove(),5500);if(window.Notification?.permission==='granted')new Notification(data.titulo,{body:data.mensaje,icon:'Img/logo.png'});}
  root.querySelector('.mw-launcher').addEventListener('click',()=>drawer.classList.add('open'));root.querySelector('.mw-close').addEventListener('click',()=>drawer.classList.remove('open'));root.querySelectorAll('[data-mw-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.mwView;render();}));search.addEventListener('input',render);
  onSnapshot(query(collection(db,'avisos'),where('destinatarioUids','array-contains',user.uid),limit(60)),snap=>{const previous=new Set(messages.map(x=>x.id));messages=snap.docs.map(item=>({id:item.id,data:item.data()})).sort((a,b)=>(b.data.creadoEn?.seconds||0)-(a.data.creadoEn?.seconds||0));if(!firstSnapshot){const newest=messages.find(item=>!previous.has(item.id));if(newest)toast(newest.data);}firstSnapshot=false;render();});
});
